spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/gamehub
spring.datasource.username=postgres
spring.datasource.password=sherlyndoes?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rawg.api.key=${RAWG_API_KEY}